language: php

php:
    - 7.3

sudo: false

cache:
  directories:
    - node_modules
    - vendor

services:
  - mysql

before_script:
    - cp .env.travis .env
    - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS travis;'
    - composer self-update
    - composer install --prefer-source --no-interaction --dev
    - php artisan migrate --no-interaction -vvv

script:
    - vendor/bin/phpunit

after_success:
    - bash <(curl -s https://codecov.io/bash)

addons:
    artifacts: true