language: php

php:
    - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS travis;'

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    - cp .env.travis .env

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
